apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      name: heimdall
  template:
    metadata:
      labels:
        name: heimdall
    spec:
      serviceAccountName: heimdall
      containers:
        - name: heimdall
          image: quay.io/sfrancog/heimdall-operator:master
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - heimdall
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: DOCKER_CONFIG
              value: "/usr/local/docker"
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "heimdall"
          volumeMounts:
            - mountPath: /tmp/docker
              name: heimdall-dockercfg
      volumes:
        - name: heimdall-dockercfg
          secret:
            secretName: heimdall-dockercfg